In [124]:
import numpy as np
import random
import math
from math import exp

In [125]:
sudokuPuzzle = np.array([[0,0,0,0,3,0,6,0,0],
                         [5,0,0,9,0,0,4,0,0],
                         [0,8,0,6,0,7,0,0,9],
                         [0,7,0,0,0,0,8,0,1],
                         [0,5,0,0,8,0,0,2,0],
                         [3,0,8,0,0,0,0,5,0],
                         [1,0,0,8,0,4,0,9,0],
                         [0,0,2,0,0,6,0,0,5],
                         [0,0,9,0,1,0,0,0,0]])
#sudokuPuzzle

In [126]:
def copy_grid(sudoku):
    copiedPuzzle = []
    for i in range(len(sudoku)):
        copiedPuzzle.append(list(sudoku[i]))
    return copiedPuzzle
#copy_grid(sudokuPuzzle)

In [127]:
def square_coordinates(sudoku, r, c):
    square = []
    row = []
    square_size = int(math.sqrt(len(sudoku)))
    for i in range((r - 1) * square_size, square_size + (r - 1) * square_size  ):
        for j in range((c - 1) * square_size, square_size + (c - 1) * square_size ):
            row.append(sudoku[i][j])
        square.append(row)
        row = []
    return square
            
    
#square_coordinates(sudokuPuzzle, 3, 3)
    

In [128]:
def nonFixedPositions(sudoku, r, c):
    emptyIndices = []
    square_size = int(math.sqrt(len(sudoku)))
    square = square_coordinates(sudoku, r, c)
    for i in range(square_size):
        for j in range(square_size):
            if(square[i][j] == 0):
                emptyIndices.append([i, j])
    return emptyIndices
#nonFixedPositions(sudokuPuzzle, 1, 2)

In [129]:
def pickRandomUnfixedPosition(sudoku, i, j):
    randomIndex = random.randint(0, len(nonFixedPositions(sudoku, i, j)) - 1)
    return nonFixedPositions(sudoku, i, j)[randomIndex]
pickRandomUnfixedPosition(sudokuPuzzle, 1, 2)

[1, 2]

In [130]:
def possibleNumsList(sudoku, i, j):
    nonPossibilities = []
    possibilities = []
    square = square_coordinates(sudoku, i, j)
    for row in square:
        for num in row:
            if (num != 0):
                nonPossibilities.append(num)
    for n in range(1, len(sudoku) + 1):
        if (n not in nonPossibilities):
            possibilities.append(n)
    return possibilities

#possibleNumsList(sudokuPuzzle, 2, 2)

In [143]:
def fillBox(sudoku, i, j):
    box = square_coordinates(sudoku, i, j)
    listOfPossibilities = possibleNumsList(sudokuPuzzle, i, j)
    notFixedPositions = nonFixedPositions(sudoku, i, j)
    for x in range(len(notFixedPositions)):
       box[notFixedPositions[x][0]][notFixedPositions[x][1]] = listOfPossibilities[x]
    return np.array(box)
fillBox(sudokuPuzzle, 1, 2)

array([[1, 3, 2],
       [9, 4, 5],
       [6, 8, 7]])

In [157]:
def fillAllBoxes(sudoku):
    randomSudoku = []
    square_size = int(math.sqrt(len(sudoku)))
    for i in range(1, square_size + 1):
        for j in range(1, square_size + 1):
            randomSudoku.append(fillBox(sudoku, i, j))
    return randomSudoku
fillAllBoxes(sudokuPuzzle)

[array([[1, 2, 3],
        [5, 4, 6],
        [7, 8, 9]]),
 array([[1, 3, 2],
        [9, 4, 5],
        [6, 8, 7]]),
 array([[6, 1, 2],
        [4, 3, 5],
        [7, 8, 9]]),
 array([[1, 7, 2],
        [4, 5, 6],
        [3, 9, 8]]),
 array([[1, 2, 3],
        [4, 8, 5],
        [6, 7, 9]]),
 array([[8, 3, 1],
        [4, 2, 6],
        [7, 5, 9]]),
 array([[1, 3, 4],
        [5, 6, 2],
        [7, 8, 9]]),
 array([[8, 2, 4],
        [3, 5, 6],
        [7, 1, 9]]),
 array([[1, 9, 2],
        [3, 4, 5],
        [6, 7, 8]])]

In [167]:
def formalFills(A):
    B=[]
    for i in range(3):    
        B.append(np.concatenate((A[0][i], A[1][i], A[2][i]), axis=None).tolist())
    for i in range(3):    
        B.append(np.concatenate((A[3][i], A[4][i], A[5][i]), axis=None).tolist())
    for i in range(3):    
        B.append(np.concatenate((A[6][i], A[7][i], A[8][i]), axis=None).tolist())

formalFills(fillAllBoxes(sudokuPuzzle))  

[array([[1, 2, 3],
        [5, 4, 6],
        [7, 8, 9]]),
 array([[1, 3, 2],
        [9, 4, 5],
        [6, 8, 7]]),
 array([[6, 1, 2],
        [4, 3, 5],
        [7, 8, 9]]),
 array([[1, 7, 2],
        [4, 5, 6],
        [3, 9, 8]]),
 array([[1, 2, 3],
        [4, 8, 5],
        [6, 7, 9]]),
 array([[8, 3, 1],
        [4, 2, 6],
        [7, 5, 9]]),
 array([[1, 3, 4],
        [5, 6, 2],
        [7, 8, 9]]),
 array([[8, 2, 4],
        [3, 5, 6],
        [7, 1, 9]]),
 array([[1, 9, 2],
        [3, 4, 5],
        [6, 7, 8]])]