In [4]:
import numpy as np
import random
import math
from math import exp

In [5]:
sudokuPuzzle = np.array([[0,0,0,0,3,0,6,0,0],
                         [5,0,0,9,0,0,4,0,0],
                         [0,8,0,6,0,7,0,0,9],
                         [0,7,0,0,0,0,8,0,1],
                         [0,5,0,0,8,0,0,2,0],
                         [3,0,8,0,0,0,0,5,0],
                         [1,0,0,8,0,4,0,9,0],
                         [0,0,2,0,0,6,0,0,5],
                         [0,0,9,0,1,0,0,0,0]])
box_size = int(math.sqrt(len(sudokuPuzzle)))
#sudokuPuzzle

In [6]:
def copy_grid(sudoku):
    copiedPuzzle = []
    for i in range(len(sudoku)):
        copiedPuzzle.append(list(sudoku[i]))
    return copiedPuzzle
#copy_grid(sudokuPuzzle)

In [7]:
def print_grid(grid):
    for num in grid:
        print(num)

In [8]:
def square_coordinates(sudoku, r, c):
    square = []
    row = []
    square_size = int(math.sqrt(len(sudoku)))
    for i in range((r - 1) * square_size, square_size + (r - 1) * square_size  ):
        for j in range((c - 1) * square_size, square_size + (c - 1) * square_size ):
            row.append(sudoku[i][j])
        square.append(row)
        row = []
    return square
            
    
#square_coordinates(sudokuPuzzle, 3, 3)
    

In [9]:
def nonFixedPositions(sudoku, r, c):
    emptyIndices = []
    square_size = int(math.sqrt(len(sudoku)))
    square = square_coordinates(sudoku, r, c)
    for i in range(square_size):
        for j in range(square_size):
            if(square[i][j] == 0):
                emptyIndices.append([i, j])
    return emptyIndices
#nonFixedPositions(sudokuPuzzle, 1, 2)

In [10]:
def pickRandomUnfixedPosition(sudoku, i, j):
    randomIndex = random.randint(0, len(nonFixedPositions(sudoku, i, j)) - 1)
    return nonFixedPositions(sudoku, i, j)[randomIndex]
pickRandomUnfixedPosition(sudokuPuzzle, 1, 2)

[0, 0]

In [11]:
def possibleNumsList(sudoku, i, j):
    nonPossibilities = []
    possibilities = []
    square = square_coordinates(sudoku, i, j)
    for row in square:
        for num in row:
            if (num != 0):
                nonPossibilities.append(num)
    for n in range(1, len(sudoku) + 1):
        if (n not in nonPossibilities):
            possibilities.append(n)
    return possibilities

#possibleNumsList(sudokuPuzzle, 2, 2)

In [12]:
def fillBox(sudoku, i, j):
    box = square_coordinates(sudoku, i, j)
    listOfPossibilities = possibleNumsList(sudokuPuzzle, i, j)
    notFixedPositions = nonFixedPositions(sudoku, i, j)
    for x in range(len(notFixedPositions)):
       box[notFixedPositions[x][0]][notFixedPositions[x][1]] = listOfPossibilities[x]
    return np.array(box)
#fillBox(sudokuPuzzle, 1, 2)

In [13]:
def fillAllBoxes(sudoku):
    A = []
    B = []
    square_size = int(math.sqrt(len(sudoku)))
    for i in range(1, square_size + 1):
        for j in range(1, square_size + 1):
            A.append(fillBox(sudoku, i, j))

###copied this part completely cause nahi ho raha tha, we need to 
###figure a better way to do this.
    for i in range(3):    
        B.append(np.concatenate((A[0][i], A[1][i], A[2][i]), axis=None).tolist())
    for i in range(3):    
        B.append(np.concatenate((A[3][i], A[4][i], A[5][i]), axis=None).tolist())
    for i in range(3):    
        B.append(np.concatenate((A[6][i], A[7][i], A[8][i]), axis=None).tolist())
    return B
print_grid(fillAllBoxes(sudokuPuzzle))
print_grid(sudokuPuzzle)


[1, 2, 3, 1, 3, 2, 6, 1, 2]
[5, 4, 6, 9, 4, 5, 4, 3, 5]
[7, 8, 9, 6, 8, 7, 7, 8, 9]
[1, 7, 2, 1, 2, 3, 8, 3, 1]
[4, 5, 6, 4, 8, 5, 4, 2, 6]
[3, 9, 8, 6, 7, 9, 7, 5, 9]
[1, 3, 4, 8, 2, 4, 1, 9, 2]
[5, 6, 2, 3, 5, 6, 3, 4, 5]
[7, 8, 9, 7, 1, 9, 6, 7, 8]
[0 0 0 0 3 0 6 0 0]
[5 0 0 9 0 0 4 0 0]
[0 8 0 6 0 7 0 0 9]
[0 7 0 0 0 0 8 0 1]
[0 5 0 0 8 0 0 2 0]
[3 0 8 0 0 0 0 5 0]
[1 0 0 8 0 4 0 9 0]
[0 0 2 0 0 6 0 0 5]
[0 0 9 0 1 0 0 0 0]


In [14]:
filledSudoku = fillAllBoxes(sudokuPuzzle)
filledSudokuCopy = copy_grid(filledSudoku)
#filledSudoku

In [15]:
##Cost is the numbers that are missing from the line
"""for example in line 1 [1, 2, 3, 1, 3, 2, 6, 1, 2]
numbers 4, 5, 7, 8, 9 are missing, so cost = 5

"equate cost to the number of
constraint violations"
"""
def costOfRow(sudoku):
    costList = []
    for i in range(len(sudoku)):
        row = sudoku[i]
        cost = 0
        for num in range(len(row)):
            if row.count(num + 1) == 0:
                cost += 1
        costList.append(cost)
    return sum(costList)
costOfRow(filledSudoku)

36

In [16]:
def costOfColumn(sudoku):
    costList = []
    transposedSudoku = np.transpose(sudoku)
    for i in range(len(sudoku)):
        col = transposedSudoku[i]
        cost = 0
        for num in range(len(col)):
            if col.tolist().count(num + 1) == 0:
                cost += 1
        costList.append(cost)
    return sum(costList)
costOfColumn(filledSudoku)

21

In [17]:
def totalCost(sudoku):
    return costOfRow(sudoku) + costOfColumn(sudoku)
totalCost(filledSudoku)

57

In [18]:
def changeCoordinates(i1, j1, i2, j2):
    return [(i1 - 1) * box_size + i2 , (j1 - 1) * box_size + j2]
#changeCoordinates(2,2,0,3)

In [19]:
def swapCells(sudoku):
    swapped_sudoku = copy_grid((sudoku))
    sudoku_length = len(sudoku)
    box_length = int((sudoku_length) ** (1/2.0))
    #choose a random box
    box_coordinate_1 = random.randint(1, box_length)
    box_coordinate_2 = random.randint(1, box_length)
    #box = square_coordinates(sudoku, box_coordinate_1, box_coordinate_2)
    unfixedPositionList = nonFixedPositions(sudokuPuzzle, box_coordinate_1, box_coordinate_2)

    #choose 2 random cells in non fixed positions of randomly selected box
    coordinate1 = random.randint(0, len(unfixedPositionList) - 1)
    cell1_coordinates = unfixedPositionList[coordinate1]
    coordinate2 = random.randint(0, len(unfixedPositionList) - 1)
    while(coordinate1 == coordinate2):
        coordinate2 = random.randint(0, len(unfixedPositionList) - 1)
    cell2_coordinates = unfixedPositionList[coordinate2]

    revised_cell1_coordinates = changeCoordinates(box_coordinate_1, box_coordinate_2, cell1_coordinates[0], cell1_coordinates[1])
    revised_cell2_coordinates = changeCoordinates(box_coordinate_1, box_coordinate_2, cell2_coordinates[0], cell2_coordinates[1])
    # print(revised_cell1_coordinates)
    # print(revised_cell2_coordinates)
    # print_grid(swapped_sudoku)
    # print()
    #performing the swap
    swapped_sudoku[revised_cell1_coordinates[0]][revised_cell1_coordinates[1]], swapped_sudoku[revised_cell2_coordinates[0]][revised_cell2_coordinates[1]] = \
    swapped_sudoku[revised_cell2_coordinates[0]][revised_cell2_coordinates[1]], swapped_sudoku[revised_cell1_coordinates[0]][revised_cell1_coordinates[1]]
    # print_grid(swapped_sudoku)
    # print()
    return swapped_sudoku 
swapCells(filledSudokuCopy)
# print_grid(filledSudokuCopy)

[[1, 2, 3, 1, 3, 2, 6, 1, 2],
 [5, 4, 6, 9, 4, 5, 4, 3, 5],
 [7, 8, 9, 6, 8, 7, 7, 8, 9],
 [1, 7, 2, 1, 2, 3, 8, 3, 1],
 [4, 5, 6, 4, 8, 5, 4, 2, 6],
 [3, 9, 8, 6, 7, 9, 7, 5, 9],
 [1, 3, 4, 8, 2, 4, 1, 9, 2],
 [5, 6, 2, 3, 5, 6, 3, 4, 5],
 [8, 7, 9, 7, 1, 9, 6, 7, 8]]

In [20]:
# Simulated annealing performs the latter using what’s called an acceptance probability. 
# The acceptance probability is used to determine whether we want to move to a neighbouring state or not. 
# There are a few basic properties of the acceptance probability.

# If the neighbouring state has lesser or equal cost, then we will always move to it.

# If it has greater cost, we will only move to it with a certain probability. 
# Otherwise we’ll stay where we are and choose another neighbour. 
# We define the cost delta denoted by Δc, which is simply the current cost subtracted from the neighbour cost, 
# and a parameter t, which stands for temperature, and influences how likely we are to accept the neighbouring state.

In [28]:
#anneal algo (STILL NEED TO UNDERSTAND)
def recocidoSimulado(sudo):        
    sudoCopy = copy_grid(sudo)        
    costs = 0    
    temp = 150 
    while temp > 1 :        
        changeProb = 0        
        iterations = 2000
        for i in range(iterations) :            
            if totalCost(sudoCopy) == 0:
                print("Sudoku solved")
                return sudoCopy                
            sudoAfter = swapCells(sudoCopy)
            delta = totalCost(sudoAfter) - totalCost(sudoCopy)            
            if (delta <= 0):
                sudoCopy = sudoAfter
            else :
                uniformValue = random.uniform(0, 1)
                if (uniformValue <= exp(-30 * delta/temp)):
                    #changeProb += 1
                    sudoCopy = sudoAfter            
            costs = (totalCost(sudoCopy))
            print(costs)
        temp = 0.9 * temp  
    return sudoCopy
recocidoSimulado(filledSudoku)

55
55
51
49
49
49
48
46
47
47
43
42
41
41
41
41
41
40
40
40
40
40
39
39
37
36
38
40
40
39
37
39
40
40
40
38
38
38
38
37
38
38
40
41
43
42
41
42
43
42
41
40
43
43
44
42
41
42
42
43
43
41
43
43
43
42
40
37
37
40
41
42
40
39
39
40
42
40
39
38
39
40
40
40
41
39
38
39
37
37
36
35
37
40
42
43
45
46
46
46
46
45
44
46
46
46
45
46
47
46
45
44
43
42
42
42
42
44
46
48
48
49
49
48
49
48
44
44
42
42
42
45
44
44
43
42
42
41
39
39
38
38
38
37
38
39
42
41
42
42
43
44
43
42
43
43
43
44
44
44
44
44
45
45
46
47
48
46
44
44
45
44
43
43
43
43
40
40
41
40
40
41
40
39
36
36
35
37
35
33
32
33
35
37
37
36
35
35
35
35
35
35
34
35
36
34
34
34
37
37
37
37
38
36
37
37
37
39
40
40
42
41
41
41
41
42
43
43
43
44
43
43
43
45
45
46
45
47
45
44
42
43
44
44
46
47
49
48
47
46
45
45
43
43
41
39
41
40
38
38
36
36
35
36
35
36
36
37
37
38
38
37
37
39
39
39
37
39
39
41
41
42
43
43
43
46
45
42
42
41
41
41
41
40
40
42
42
41
41
44
40
40
40
40
39
38
35
35
34
34
34
34
34
35
35
34
34
34
34
35
36
38
39
39
39
40
40
40
37
38
41
44
43
4

[[4, 9, 7, 1, 3, 5, 6, 8, 2],
 [5, 1, 6, 9, 2, 8, 4, 3, 7],
 [2, 8, 3, 6, 4, 7, 5, 1, 9],
 [9, 7, 4, 2, 5, 3, 8, 6, 1],
 [6, 5, 1, 4, 8, 9, 7, 2, 3],
 [3, 2, 8, 7, 6, 1, 9, 5, 4],
 [1, 3, 5, 8, 7, 4, 2, 9, 6],
 [8, 4, 2, 3, 9, 6, 1, 7, 5],
 [7, 6, 9, 5, 1, 2, 3, 4, 8]]

In [3]:
solution = recocidoSimulado(filledSudoku)
print_grid(solution)

NameError: name 'filledSudoku' is not defined